name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
