name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: cosSumCompute
      id: cossumcompute
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: cosSumCompute
        setup-command: ''
        command: make test
        timeout: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COSSUMCOMPUTE_RESULTS: "${{steps.cossumcompute.outputs.result}}"
      with:
        runners: cossumcompute
